apiVersion: v1
kind: Service
metadata:
  name: validation
  namespace: testbed
spec:
  type: NodePort
  selector:
    app: validation
  ports:
    - name: web8080
      protocol: TCP
      port: 8080
      targetPort: 8080