spring:
  application:
    name: ui-service

  profiles:
    active: dev

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
  instance:
    preferIpAddress: true


