spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input-stream:
          destination: validated
          contentType: application/json
        processed-output-stream:
          destination: processed
          contentType: application/json
        deadletter-output-stream:
          destination: deadletter
          contentType: application/json