spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input-stream:
          destination: source
          contentType: application/json
        validated-output-stream:
          destination: validated
          contentType: application/json
        deadletter-output-stream:
          destination: deadletter
          contentType: application/json
server:
  port:
    8080