spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:

        - id: web-ui-envpage
          uri: lb://ui-service/environment/
          predicates:
            - Path=/environment/*

        - id: management-graphql
          uri: lb://management-service/graphql
          predicates:
            - Path=/graphql/*

        - id: aggregation-subscription
          uri: lb:ws://aggregation-service/subscribe
          predicates:
            - Path=/subscription/aggregation/*

        - id: topology-subscription
          uri: lb:ws://discovery-service/subscribe
          predicates:
            - Path=/subscription/topology/*

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
  instance:
    preferIpAddress: true

server:
  port: 80
