aggregation:
  service:
    sync:
      period: 5000
    retention:
      period: 60
    purge:
      period: 300000
    aggregation:
      window:
        size: 1000
    endpoints:
      environment-update: /subscription/aggregation/*

spring:
  application:
    name: aggregation-service
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/thesis
    driver-class-name: org.postgresql.Driver
    username: thesis
    password: thesis

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        format_sql: true
        default_schema: ${spring.datasource.schema-name}
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
  instance:
    preferIpAddress: true

management:
  service:
    serviceId: management-service

