spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input-stream:
          destination: source
          contentType: application/json
        output-stream:
          destination: ingest
          contentType: application/json
