spring:
  application:
    name: correlation-service
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/thesis
    driver-class-name: org.postgresql.Driver
    username: thesis
    password: thesis

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        default_schema: ${spring.datasource.schema-name}
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
  instance:
    preferIpAddress: true

correlation:
  service:
    serviceId: correlation-service